config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/thank_you'

  devise_for :users
  resources :users
  get 'static_pages/conversions'

  get 'static_pages/recipebox'

  get 'static_pages/aboutproject'

  get 'static_pages/aboutme'

  get 'static_pages/contact'

  mount Ckeditor::Engine => '/ckeditor'
  resources :blogs
  get 'static_pages/index'
  root 'static_pages#index'

  post 'static_pages/thank_you'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)
      if user.admin?
         can :manage, :all
      else
         can :read, :all
      end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, :to => :data

  validates_presence_of :data
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  mount_uploader :data, CkeditorAttachmentFileUploader, :mount_on => :data_file_name

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, :mount_on => :data_file_name

  def url_content
    url(:content)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  def active_for_authentication?
  	super && approved?
  end

  def inactive_message
  	if !approved?
  		:not_approved
  	else
  		super # Use whatever other message
  	end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  	rescue_from CanCan::AccessDenied do |exception|
		redirect_to main_app.root_url, :alert => exception.message
	end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, :except => [:show, :index]
  load_and_authorize_resource

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title, :body)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end

  def thank_you
  	@name = params[:name]
  	@email = params[:email]
  	@message = params[:message]
  	ActionMailer::Base.mail(:from => @email, 
  		:to => 'differentfamiliarflavors@gmail.com',
  		:subject => "A new contact form message from #{@name}",
  		:body => @message).deliver_now
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, :except => [:show, :new]
  load_and_authorize_resource

  # GET /users
  # GET /users.json
  def index
    if params[:approved] == "false"
      @user = User.where(approved: false)
    else
      @user = User.all
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/_form.html.erb
<%= simple_form_for(blog) do |f| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.input :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.input :body, :as => :ckeditor, input_html: {:ckeditor => {:toolbar => 'FULL'}}, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<% if current_user && current_user.admin? %>
	<%= render 'form', blog: @blog %>
<% end %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Blog</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= blog.title %></td>
        <td><%= raw(blog.body) %></td>
        <td><%= link_to 'More', blog %></td>

        <% if current_user && current_user.admin? %>
        <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
        <td><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if current_user && current_user.admin? %>
<%= link_to 'New Post', new_blog_path %>
<% end %>

  <!-- note, adding 'raw' is only good if admin inputted info, not for user input. Check out sanitize gem for better security.-->

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<% if current_user && current_user.admin? %>
	<%= render 'form', blog: @blog %>
<% end %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @blog.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= raw(@blog.body) %> 

  <!-- note, adding 'raw' is only good if admin inputted info, not for user input. Check out sanitize gem for better security.-->

</p>
<% if current_user && current_user.admin? %>
<%= link_to 'Edit', edit_blog_path(@blog) %> |
<% end %>
<%= link_to 'Back', blogs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Different Familiar Flavors</title>
    


    <!--<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">-->
      


  

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/css?family=Caveat" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">
    <link rel="icon" type="image/png" href="favicon.png">
    

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>


    <!--<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>-->
  </head>

  <body>
  <div class="top container-fluid">
  <h1><%= link_to('Different Familiar Flavors', root_path) %></h1>
  </div>
  
  <!--nav bar-->
  <nav class="navbar navbar-default" role="navigation" style="background-color: #fff;">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <!-- http://www.w3schools.com/bootstrap/bootstrap_navbar.asp-->
    <div class="navbar-header">
      <button id="nav-toggle-button" type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">  
        <li><%= link_to "Blog", blogs_path %></li>
        <li><%= link_to "Travel Journals", blogs_path %></li>
        <li class="dropdown">
          <a href="" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Tools <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Conversion Table", static_pages_conversions_path %></li>
            <li><%= link_to "Recipe Box", static_pages_recipebox_path %></li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">About<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "The DFF Project", static_pages_aboutproject_path %></li>
            <li><%= link_to "About me", static_pages_aboutme_path %></li>
          </ul>
        </li>
        <li><%= link_to "Contact", static_pages_contact_path %></li>
        <li> <!--log in/log out-->
          <% if user_signed_in? %>
            <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
          <% else %>
            <%= link_to('Login', new_user_session_path) %>
          <% end %>
        </li><!--end: log in/log out-->
      </ul>  
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
  
<!--nav bar ends-->


<% if notice %>
  <p class="notice"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert"><%= alert %></p>
<% end %>

<%= yield %>

<footer>
  &copy; 2016 Different Familiar Flavors
</footer>

  <!-- Can place script tags with JavaScript files here -->


  </body>
</html>

app/views/static_pages/aboutme.html.erb
<h1>Under Construction</h1>

app/views/static_pages/aboutproject.html.erb
<h1>About The DFF project</h1>

<p>2016 is a year of upheaval and change for me. I bid my posh banking job goodbye and started a new introspection and career search, I got married to a wonderful man (he will occassionally pop up as 'hubby' in my posts), I started learning one of the most gramatically complicated languages in the world (German), and, I started learning front and back end web development. During this transition period, I decided to work on something I've always been interested in - namely, food, photography, and web development. Well, put everything together, and voila! there is //The DFF Project//.</p>
<p>So, what exactly is //The DFF Project//?</p><p> DFF is an acronym of Different Familiar Flavors. I have been fortunate to have traveled and lived extensively in many different parts of the world. I was introduced to various cuisines, and as such, the various flavor profiles of different cultures have left their marks on me. While I enjoy trying out new foods, I sometimes find myself wishing that I could just resample some of the familiar flavors of a taste memory from a world away. The goal of //The DFF Project// is to carry with me these flavors to a different place and time. It is as much to share these flavors in this new place as it a way for my friends and family a world or two away to follow and enjoy my food discoveries.</p>
<p>So how will this project take shape? It is still a discovery process for me. The main goal is sharing the flavors I know and discovering new flavors. This is likely to take shape in the form of a blog and a recipe exchange. But, stay tuned, as it is likely to ever evolve. The other goal is standardization and reproduction. (How much exactly is a cup anyways? Did you know that there are different "spoon" measures in the world? And, how do you get that ingredient?). </p> 
<p>Process: I am probably taking the longest and hardest way around in building this project. Forgoing Blogger, Wix, WordPress, and other useful services that are there for a reason, I am building everything on this website from scratch (Hallooo~, HTML, CSS, Javascript, Ruby! Let's chum up. And you too, Google!). I have just completed a six month online web development course and my goal is to utilize what I have learned. The downside: frustration and likely slow progress. The upside? You can see my website evolve and see the triumphs and frustrations of a first time coder! My updates will be logged below.</p>

<h1>Growing Pains: Triumphs and grumblings of a first time coder</h1>
<h4>Resources and References used so far:</h4>
<p>CareerFoundry. Bootstrap. Github. Ruby (Gems: Devise, CanCanCan, CKEditor). Sublime Text. Terminal. W3JSchool. stackoverflow.</p>
<h4>To-do List:</h4>
<p>In no particular order:</p>
	<ul>
			<li><s>Create an accordian to house my musings</s>(02.01.2017)</li>
			<li>Choose color scheme</li>
			<li><s>Create an "under construction" page </s> (02.01.2017)</li>
			<li>Edit my Favicon</li>
			<li>Add a 'forget password' link</li>
			<li>Add mail actions for signups</li>
			<li>Create a contact page</li>
			<li>Create an index page</li>
			<li>Add Chinese</li>
			<li>Format the blog index page</li>
			<li>Format the blog viewing page</li>
			<li><s>Add a Travelogs category</s>(03.01.2017)</li>
			<li>Work on About Me</li>
			<li>Style the log in pages</li>
			<li>Print function for recipes</li>
			<li>Comment function for signed in guests</li>
	</ul>
<h4>Work Log</h4>

<!--Accordian start-->
<button class="accordion">04.01.2017 Navigation bar styled and Contact Form created </button>
	<div class="panel">
	<p> A bow to all designers. Designing and creating beautiful layouts is harder than I imagined. Played all day yesterday and today trying to do the correct formating, but it definitely takes quite a bit of time!</p>
	<p> Also, decided to create the contact page. Currently trying to work through the intricacies of recaptcha.</p>
	<p> Resource consulted: https://www.sitepoint.com/quick-tip-add-recaptcha-to-your-rails-application/ </p>
</div>

<button class="accordion">02.01.2016 To-do List created as well as a favicon and accordian </button>
	<div class="panel">
		<p>It took a bit longer to put the Favicon icon up than I had hoped. The trick is to put the .png file in the right position - and for Ruby on Rails apps, it's in the public folder. </p>
		<p>Also finally put in the accordian. Can't believe I forgot how to add javascript. Need to figure out the 'correct' way than what I have done here.</p>
		<p>Resource Consulted: http://www.w3schools.com/howto/howto_js_accordion.asp </p>
	</div>

<button class="accordion">30.12.2016 And... we are now live! </button>
	<div class="panel">
  	<p><b><23:10: Finally whole site working!> </b>Couldn't sleep. Sat in the dark trying to figure out what the problem was. Hubby sat down next to me and quietly listened to the issue. "It had worked perfectly on my local machine!"" I complained.</p>
		<p>"You must have forgotten a database migration," he said, looking through my heroku log.</p>
		<p>Time to eat humble pie. I thought that I had gotten quite familiar with database migrations, but seems like there is always more to learn! Ran the requisite migration onto heroku, and finally, all is working.</p>
		<p><b><17:00: Uploaded onto Heroku!></b> One day before the new year, and my website is live! Quickly noticed however that there are still access problems. The blog and sign-in sessions are totally down. </p>
		<p><b><16:00: Successfully implemented admin approval></b>This is a bit of a work around. While in beta-version, I would like to invite(drag in) some friends to help test the site. However, to spare the poor guest visitor from having to sign up for something that is not yet working yet, I have added a large disclaimer. All accounts will need be first approved by me. I am sure this is not best practice, but hopefully this is only a temporary state!</p><p>Resource consulted: https://github.com/plataformatec/devise/wiki/How-To:-Require-admin-to-activate-account-before-sign_in </p>
		<p><b><10:45: Successfully configured admin rights!> </b> This was harder than I had expected. The culprit was a small 'a' - I had mistakenly mispelled 'boolean' as 'booleen.' This had totally messed up my database migrations. Well, first I had to find out why everyone had admin rights even when they were not supposed to. Then, once I found the problem, I had to get up close and personal with database migrations. Well, now I know how they work, so all in all, a foregone hour that was well worth it. </p>
</div>
<button class="accordion">29.12.2016 Reviewing authentication and authorization</button>
	<div class="panel">
  	<p><p><b><16:00></b> I am getting closer and closer to posting my website online! (Rub my hands in glee). I have finally set up authentication and authorization, but have yet to test them. At least theoretically now I have sole proporiety on writing and editing blog posts. Once that's done, I can finally load the whole thing online. Can't wait for that! Oh, and I probably should put in a why I'm doing this project onto this page, because at this point, it has definitely got to be the ugliest site on the internet. </p>
  </div>
<button class="accordion">26.12.2016 Remembering mobile first and the fallability of tutorials</button>
	<div class="panel">
		<p><p><b><18:10></b> Tutorials, very unfortunately are not almighty. Tinkered a very long time to figure out how to upload photos on CKEditor. Through lots of googling and hubby help, finally realized that one important app (Imagemagick) was missing. Then, there was an error with a version 3.6 of Minimagik, and 3.5 is necessary. Finally, need to change a line in uploader file. <br> Need to learn how to google better - seems like the trick really is copying in error message verbatim! - Sometimes simple is best. </p>
		<p><b>Next Goal:</b> I am delaying adding admin rights until tomorrow. Will be re-tackling the materials from CareerFoundry.</p>
		<p><b><13:55></b> Hooray, mobile first nav bar finally completed!! Thank you, W3JSchool! Felt like wasted yesterday as had to totally scrap the nav bar that hubby and I spent several hours debugging. But, definitely a good learning lesson to plan ahead and not to forget that we're in the age of the mobile!</p>
		<p>Next goal: set an administrator so that only I can post on blogs. Also, be able to upload photos on CKEditor. </p>
		<p> Resource consulted: https://scotch.io/tutorials/build-a-blog-with-ruby-on-rails-part-2 )  </p>
</div>

<button class="accordion">25.12.2016 The blog model and the art of creating entries</button>
	<div class="panel">
		<p>Merry Christmas! Today I woke up to the satifaction that I had completed my CKEDITOR installation. (Resource: https://scotch.io/tutorials/build-a-blog-with-ruby-on-rails-part-1 ) HoHoHo. But then realized that my toolbar doesn't work anymore. The dropdown parts have totally disappeared. Ack! Spent pre-Christmas dinner trying to figure out. Hubby comes to rescue. Many christmas cookies later finally solved issue. Before we retired to sleep, hubby makes the oberservation - hmm... what will you doing for mobile? Hovering doesn't work very well there.</p><p>Oh man. Seriously?</p>
	</div>

<button class="accordion">
14.12.2016 Birth of The DFF Project</button>
<div class="panel">
	<p><b><13:52:> $ rails new DFF -T </b></p>
</div>

<script>
  var acc = document.getElementsByClassName("accordion");
	var i;

	for (i = 0; i < acc.length; i++) {
    acc[i].onclick = function(){
        this.classList.toggle("active");
        this.nextElementSibling.classList.toggle("show");
  }
}
</script>

<!--Accordian Ends-->

app/views/static_pages/contact.html.erb
<h1>Leave a message!</h1>

<%= flash[:notice] %>

<%= form_tag("/static_pages/thank_you") do%>
<div class="row">
	<div class="col-md-4">
		<div class="form-group">
			<%= label_tag :name %>
			<%= text_field_tag :name, nil, class: "form-control", placeholder: "Enter Name" %>
		</div>
		<div class="form-group">
			<%= label_tag :email, "Email Address" %>
			<%= text_field_tag :email, nil, class: "form-control", placeholder: "Enter Email" %>
		</div>
		<div class="form-group">
			<%= label_tag :message %>
			<%= text_area_tag :message, nil, class: "form-control", placeholder: "Enter Message" %>
		</div>
	</div>
</div>

<%= submit_tag "Send" %>
<% end %>

app/views/static_pages/conversions.html.erb
<h1>Under Construction</h1>

app/views/static_pages/index.html.erb
<main>
	<div class="hero">
		<!--<h1>Different Familiar Flavors</h1>
		<p>Find me in app/views/static_pages/index.html.erb</p>-->
		<%= image_tag("Japan-1-3.jpg", class: "hero") %>
	</div>
</main>

app/views/static_pages/recipebox.html.erb
<h1>Under Construction</h1>

app/views/static_pages/thank_you.html.erb
    <p>Thank you. We have received your message and will respond as soon as possible.</p>

app/views/users/_form.html.erb
<%= simple_form_for(@user) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :first_name %>
    <%= f.input :last_name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Users awaiting approval', :action => "index", :approved => "false" %>

<table>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.approved %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>